### ISSUE TITLE
Error while trying to unshelve to another branch in the same workspace

### ISSUE THREAD

**Issue by gitzko** [Jezusfan/MultiMerge#7]
Hi, I get this error while trying to unshelve a shelveset to another branch which was branched from the source branch where the shelveset resides.

"Index and length must refer to a location within the string "

This pops up in a VS 2022 message box.

**Comment by shuelsmeier** [comment]
Hi, I already have a hunch where the problem lies. The name of your workspace probably has less than 15 characters. I will try to provide a fix in the next few days.

**Comment by keyrad-abasi** [comment]
I have the same issue... Out of a sudden the extension got out of order with aforementioned error.  
The error occurred in **VS 2022**!  
@shuelsmeier I've successfully used this extension several times, why should it stop working now? Even tried the same CS that successfully un-shelved to another branch, but now even that CS raises this error.  
I guess something is related to latest update of VS 2022, because besides that, nothing happened. 
I currently have VS 2022 17.10.4

![multimerge](https://github.com/user-attachments/assets/b29346fb-44c3-4a8d-b560-c19efeda37aa)

**Comment by agriaszabi** [comment]
Hi,
I am facing with the same issue while trying to merge the content of a large shelveset to another branch. I am not able to workaround it by checking in on another branch so I am really looking forward for a fix. 
Could you please give a rough estimation on how much time would it take to fix it?

Thank you in advance!

**Comment by shuelsmeier** [comment]
Hi, i will try to provide one this evening...

**Comment by Jezusfan** [comment]
Thanks for the feedback & quick fix. I've released a new version.

**Comment by agriaszabi** [comment]
Thank you! It works now! Good Job. Very useful tool.

Jezusfan ***@***.***> ezt írta (időpont: 2024. júl. 25., Cs,
1:00):

**Comment by gitzko** [comment]
In my case another "error" happened: 
Instead of unshelving to the root of target branch, it unshelves to \tfsRootTargetBranch\tfsRootOfSourceBranch
So if the source branch is C:\TFS\Auto\Ab\Dev\source it unshelves to C:\TFS\Auto\Ab\Features\VariableAuto\Auto\Ab\Dev\source.
While it should be C:\TFS\Auto\Ab\Features\VariableAuto\source for the target dir.
